version: "3.9"
services:
  site-scan:
    container_name: site-scan
    build:
      context: .
      dockerfile: ./site-scan/Dockerfile
    networks:
      - proxynet
    environment:
      SERVICE_PORT: 8080
    ports:
      - "8080:8080"

networks:
  proxynet:
    name: site-scan-network
